@baseUrl=https://localhost:5001
@applicationId=test-app

### Create Pokemon Request:
# @name createPokemonRequest

POST {{baseUrl}}/Pokemon
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
  "resourceType": "Pokemon",
  "name": "Squirtle",
  "nationalDexNo": 4,
  "secondaryType": "water"
}

### Get Pokemon Request:
@pkmnId = 7FE63223039147F5AB94ECFC8E6CC5AB
# @name getPokemonRequest
GET {{baseUrl}}/Pokemon/{{pkmnId}}
X-Ihis-SourceApplication: {{applicationId}}

### Search Pokemon by type Request:
# @name searchPokemonByTypeRequest
GET {{baseUrl}}/Pokemon?type=
X-Ihis-SourceApplication: {{applicationId}}

### Search Pokemon by name Request:
# @name searchPokemonByNameRequest
GET {{baseUrl}}/Pokemon?name:exact=Charizard
X-Ihis-SourceApplication: {{applicationId}}
